rules:
  - accept: /
    use_origin: https://askubuntu.com/
    mock_response:
      status: 200
      body: '{"rules":[{"accept":"/","origin":"http://localhost:9797","mock_response":"","mock_latency":{"mode":"swing","value":"2000","swing":"2000"}}]}'
      header: {}
    mock_latency:
      mode: swing
      value: 2000
      swing: 100
